function conditionMap = get_wm_condition_mapping(repoRoot)
%GET_WM_CONDITION_MAPPING Read the existing repository code for WM slot order.
%
% This intentionally fails if the condition order cannot be verified from
% the repository. The paired elastic-net module should not silently guess
% which residual-FIR condition slot corresponds to each WM task condition.

if nargin < 1 || isempty(repoRoot)
    repoRoot = pwd;
end

sourceFiles = { ...
    fullfile(repoRoot, 'functional_clustering', 'build_wm_contrast.m'), ...
    fullfile(repoRoot, 'code', 'residual_contrast', 'data_extract', 'PredictContrast.m'), ...
    fullfile(repoRoot, 'code', 'residual_contrast', 'core', 'PredictContrast_WM.m')};

for i = 1:numel(sourceFiles)
    if ~isfile(sourceFiles{i})
        error('Cannot verify WM condition order because source file is missing: %s', sourceFiles{i});
    end
end

txtBuild = fileread(sourceFiles{1});
txtPred  = fileread(sourceFiles{2});
txtWrap  = fileread(sourceFiles{3});

hasIdx0 = ~isempty(regexp(txtBuild, 'idx_0\s*=\s*\[1\s+2\s+3\s+4\]', 'once'));
hasIdx2 = ~isempty(regexp(txtBuild, 'idx_2\s*=\s*\[5\s+6\s+7\s+8\]', 'once'));
hasLabels = contains(lower(txtBuild), '''body''') && contains(lower(txtBuild), '''faces''') && ...
    contains(lower(txtBuild), '''places''') && contains(lower(txtBuild), '''tools''');

expectedCond = '[5 1 6 2]';
hasSixContrasts = contains(regexprep(txtPred, '\s+', ' '), ...
    'Cond = [[5 1 6 2]; [5 1 7 3]; [5 1 8 4]; [6 2 7 3]; [6 2 8 4]; [7 3 8 4]]');
hasWrapperSubtractions = contains(txtWrap, 'R(:,:,:,5) - R(:,:,:,1)') && ...
    contains(txtWrap, 'R(:,:,:,6) - R(:,:,:,2)') && ...
    contains(txtWrap, 'R(:,:,:,7) - R(:,:,:,3)') && ...
    contains(txtWrap, 'R(:,:,:,8) - R(:,:,:,4)');

if ~(hasIdx0 && hasIdx2 && hasLabels && hasSixContrasts && hasWrapperSubtractions)
    error(['Could not determine WM condition order from repository code. ', ...
           'Expected idx_0=[1 2 3 4], idx_2=[5 6 7 8], and six interaction contrasts including %s.'], ...
           expectedCond);
end

conditionMap = struct();
conditionMap.sourceFiles = sourceFiles;
conditionMap.conditionLabels = { ...
    '0bk_body', '0bk_faces', '0bk_places', '0bk_tools', ...
    '2bk_body', '2bk_faces', '2bk_places', '2bk_tools'};
conditionMap.categoryNames = {'Body', 'Face', 'Place', 'Tool'};
conditionMap.categoryAliases = { ...
    {'body'}, {'face', 'faces'}, {'place', 'places'}, {'tool', 'tools'}};
conditionMap.zeroBackIdx = [1 2 3 4];
conditionMap.twoBackIdx = [5 6 7 8];
conditionMap.loadDiffLabels = { ...
    'Body_LoadDiff', 'Face_LoadDiff', 'Place_LoadDiff', 'Tool_LoadDiff'};
conditionMap.interactionCond = [ ...
    5 1 6 2; ...
    5 1 7 3; ...
    5 1 8 4; ...
    6 2 7 3; ...
    6 2 8 4; ...
    7 3 8 4];
conditionMap.interactionCategoryPairs = nchoosek(1:4, 2);
conditionMap.interactionLabels = { ...
    'Body_LoadDiff_vs_Face_LoadDiff'; ...
    'Body_LoadDiff_vs_Place_LoadDiff'; ...
    'Body_LoadDiff_vs_Tool_LoadDiff'; ...
    'Face_LoadDiff_vs_Place_LoadDiff'; ...
    'Face_LoadDiff_vs_Tool_LoadDiff'; ...
    'Place_LoadDiff_vs_Tool_LoadDiff'};
end
