%% --- 0. Initial Setup ---
addpath(genpath('/users/rwang/CanLabCore'));
fprintf('--- Starting Step 2: Group-Level Analysis ---\n');
output_dir = '/dcs07/smart/data/HRF/bogdan_hrf/stats/fsl_noar_24vec_csf_spikes/results/WM/autocorrelation_analysis_output';

%% --- 1. Concatenate Individual Maps and Run T-test ---

% Find all the Q-statistic NIfTI files generated by Step 1
q_map_files = dir(fullfile(output_dir, '*_Q_map.nii'));
if isempty(q_map_files)
    error('No Q-statistic maps found in the output directory.');
end

% Create a cell array of full file paths
q_stat_filenames = fullfile({q_map_files.folder}, {q_map_files.name})';

fprintf('Found %d subject maps. Concatenating into 4D object...\n', length(q_stat_filenames));
group_q_stats_data = fmri_data(q_stat_filenames);

% Perform a standard two-tailed one-sample t-test
fprintf('Performing t-test...\n');
t_results_2tailed = ttest(group_q_stats_data);

% Calculate one-tailed p-values for a right-tailed test (Q > 0)
fprintf('Manually calculating right-tailed p-values...\n');
t_stats = t_results_2tailed.dat;
p_2tailed = t_results_2tailed.p;
p_1tailed = nan(size(p_2tailed));

positive_t_mask = t_stats > 0;
p_1tailed(positive_t_mask) = p_2tailed(positive_t_mask) ./ 2;

negative_t_mask = t_stats <= 0;
p_1tailed(negative_t_mask) = 1 - p_2tailed(negative_t_mask) ./ 2;

% Create a new statistic image with the correct one-tailed p-values
t_results = t_results_2tailed;
t_results.p = p_1tailed;
t_results.dat_descrip = 'Group one-sample t-test (manually corrected to right-tailed)';

%% --- 2. Save Results ---
% Save the unthresholded group maps
fprintf('Saving unthresholded group-level maps...\n');
write(t_results, 'fname', fullfile(output_dir, 'group_t_map_unthresholded.nii'), 'overwrite');

p_map_to_save = t_results;
p_map_to_save.dat = t_results.p;
p_map_to_save.dat_descrip = 'Group one-sample t-test (right-tailed p-values)';
write(p_map_to_save, 'fname', fullfile(output_dir, 'group_p_map_unthresholded.nii'), 'overwrite');

% Correct for multiple comparisons and save the thresholded map
fprintf('Applying FDR correction (q < 0.05) and saving thresholded map...\n');
t_results_fdr_corrected = threshold(t_results, .05, 'fdr');
write(t_results_fdr_corrected, 'fname', fullfile(output_dir, 'group_t_map_fdr_05.nii'), 'overwrite');

fprintf('\n--- Analysis Complete ---\n');
fprintf('Final output NIfTI files are in: %s\n', output_dir);